### ISSUE TITLE
No connection to Anel-Hut

### ISSUE THREAD

**Issue by Workerstime** [dan1-de/ioBroker.anelhut#19]
Hi,

I use the actual Version of the anel adapter (1.08) now with the actual iobroker Version (5.1.23). In the previous version it worked fine.
I have now a problem connecting to Anel-Hut (FW 7.1). The correct data for device name, device IP, UDPSendPort, UDPRecievePort, user name and password are stored in the instance. However, no connection is made. There is an error in the log: UDP Server Error: Error: bind EACCES 0.0.0.0:77 at dgram.js: 338: 20 at processTicksAndRejections (internal / process / task_queues.js: 85: 21) 

My Node.js: v12.22.0 on a Rasbipi 4

**Comment by dan1-de** [comment]
Hi @Workerstime 

i've also updated my iobroker instance today without any errors on the Anel Hut Adapter.
Thank you for providing a log message. 
Have you tried a full restart of the Raspberry ?
It is possible that the binding of the port was not released during the update.

The node version looks good. I'm using v12.22.1.

Please give a feedback if a restart solves this issue. Otherwise i will have a deeper look.

Br, 

Daniel

**Comment by Workerstime** [comment]
Hi Daniel,

thanks for your fast information.  I´ve restarted the raspi after the update. 

Now after your information i will restarted it again. But its the same. So i delete the object and the instance complete. Then i activate a new instance and device with the correct data for the device.

The LOG has now the follwoing information:
anelhut.0    2021-08-12 18:43:29.095    info    check group user admin group admin: false
anelhut.0    2021-08-12 18:43:29.090    info    check user admin pw iobroker: false,system.user.admin
anelhut.0    2021-08-12 18:43:28.904    error    UDP Server Error: Error: bind EACCES 0.0.0.0:77 at dgram.js:338:20 at processTicksAndRejections (internal/process/task_queues.js:85:21)
anelhut.0    2021-08-12 18:43:28.855    info    Adapter anelhut initialized
anelhut.0    2021-08-12 18:43:28.853    info    Found device in config: Anel-HUT | 192.168.178.xx (xx = there is the correct IP) 
anelhut.0    2021-08-12 18:43:28.853    info    Found: 1 devices in configuration
anelhut.0    2021-08-12 18:43:28.851    info    Adapter anelhut starting...
anelhut.0    2021-08-12 18:43:28.820    info    starting. Version 1.0.8 in /opt/iobroker/node_modules/iobroker.anelhut, node: v12.22.0, js-controller: 3.3.15 

I saw in the second line in the tab information "check user admin" (its ok) but "pw iobroker"  if pw = password? then the "pw iobroker" is not correct an not the pw for the device i had saved.

I hope this information wil help you to fixed the problem.

Br,
Frank

    Am Donnerstag, 12. August 2021, 16:02:19 MESZ hat dan1-de ***@***.***> Folgendes geschrieben:  
 
 


Hi @Workerstime

i've also updated my iobroker instance today without any errors on the Anel Hut Adapter.
Thank you for providing a log message.
Have you tried a full restart of the Raspberry ?
It is possible that the binding of the port was not released during the update.

The node version looks good. I'm using v12.22.1.

Please give a feedback if a restart solves this issue. Otherwise i will have a deeper look.

Br,

Daniel

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dan1-de** [comment]
Hi @Workerstime,

thank you for the quick response.
Can you try another port > 1024 eg. 1077?

Br
Daniel

**Comment by Workerstime** [comment]
Hi Daniel,

thank you for the information. I´ve changed the port 77 to 1077 and 75 to 1024 in both devices. And now I have a correct funtion. Very well.  :-) 

Can you tell me why the standard ports now unvailible? Must I reconfigure anything in my system to use the standardports? 

Br,
Frank
   Am Freitag, 13. August 2021, 13:10:12 MESZ hat dan1-de ***@***.***> Folgendes geschrieben:  
 
 


Hi @Workerstime,

thank you for the quick response.
Can you try another port > 1024 eg. 1077?

Br
Daniel

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dan1-de** [comment]
@Workerstime, 

I'm happy that it works now. In linux systems you can not bind to ports less than 1024 without root access. I assume that iobroker was running with root privileges on your system. Maybee the root privileges get lost during the iobroker update.

Br, 
Daniel
