### ISSUE TITLE
You are assigning a number to the state ... which expects a boolean.

### ISSUE THREAD

**Issue by Qlink84** [dan1-de/ioBroker.anelhut#26]
<html>
<body>

javascript.0 | 2022-10-25 18:25:18.241 | warn | at processTimers (node:internal/timers:502:7)
-- | -- | -- | --
javascript.0 | 2022-10-25 18:25:18.241 | warn | at listOnTimeout (node:internal/timers:561:11)
javascript.0 | 2022-10-25 18:25:18.241 | warn | at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1747:29)
javascript.0 | 2022-10-25 18:25:18.241 | warn | at Object.setState (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1689:20)
javascript.0 | 2022-10-25 18:25:18.240 | warn | You are assigning a number to the state "anelhut.0.Technikraum.relais.7.Status" which expects a boolean. Please fix your code to use a boolean or change the state type to number. This warning might become an error in future versions.

</body>
</html>

**Comment by dan1-de** [comment]
Hi @Qlink84,
thank you for reporting that. This is no functional blocker. I'll fix that with the next adapter release.

**Comment by dan1-de** [comment]
Fix implemented on dev branch Adapter Version 1.0.11. 
Commit: https://github.com/dan1-de/ioBroker.anelhut/commit/c909686e4137f91b64413cedcc8ba196bdf6eba0
Will be part of the next release.
