### ISSUE TITLE
no readings from temperature sensor of NET-PwrCtrl ADV (firmware 6.5)

### ISSUE THREAD

**Issue by Qlink84** [dan1-de/ioBroker.anelhut#27]
![image](https://user-images.githubusercontent.com/15886027/197837094-670f22cd-2140-4a7f-a9ca-0ae6aa5e3cd2.png)

**Comment by dan1-de** [comment]
Hi @Qlink84, 
is this the only issue ? 
Are the relais working with iobroker ?

To check the output of your NET-PwCtrl ADV could you please send me the output of the following command:

netcat -vv -l -p 2078 -u 

You have to replace 2078 with the port which is shown in the anel webinterface here:
![image](https://user-images.githubusercontent.com/52854781/199031013-41afff53-1f0c-4b47-a7d5-5a4bd439eaa7.png)

After you have entered the command the computer is listening on udp broadcast traffic. If you change now one of the inputs/outputs of the anel device, you should recieve a message in the command line.

**Comment by dan1-de** [comment]
In addition it would be sensible to update to the latest firmware 7.0.
You can download the firmware from here: 
https://de.anel.eu/index.htm?src=/support/support.htm

**Comment by Qlink84** [comment]
Hi dan1,

no that's not the only issue.
relais were only half working (see details here: https://forum.iobroker.net/topic/59416/bool-dp-wird-mit-0-1-ausgelesen-wie-in-blockly-ansteuern

long story short:

turn relais off with 0 was working, turn relais on with 1 wasn't working

however, now after i have upgraded to firmware 7.1 neither turn off with 0/false nor turn on with 1/true is working

here's netcat output:

`Connection received on 192.168.30.7 75
NET-PwrCtrl:NET-CONTROL    :192.168.30.7:255.255.255.0:192.168.30.254:0.4.163.20                        .3.118:Modem,1:Firewall,1:Unifi Switch,1:frei,1:Raspimatic,1:Weatherman,1:Sonos,                        1:Dayton,0:0:80:IO.1,0,0:IO.2,0,0:IO.3,0,0:IO.4,0,0:IO.5,0,0:IO.6,0,0:IO.7,0,0:I                        O.8,0,0:24.7▒C:NET-PWRCTRL_07.1:a:n:xor:`

here's debug output after some testing:

`<html>
<body>


 
--
anelhut.0 | 2022-11-01 16:41:24.007 | info | state anelhut.0.Technikraum.relais.8.Status changed: 0 (ack = true)
anelhut.0 | 2022-11-01 16:40:33.817 | info | state anelhut.0.Technikraum.relais.8.Status changed: 0 (ack = true)
anelhut.0 | 2022-11-01 16:40:15.551 | error | Decode Message Error: NoPass
anelhut.0 | 2022-11-01 16:40:15.551 | debug | New Message from: 192.168.30.7:75 - NET-PwrCtrl:NET-CONTROL :NoPass:Err
anelhut.0 | 2022-11-01 16:40:15.551 | error | Decode Message Error: NoPass
anelhut.0 | 2022-11-01 16:40:15.551 | debug | New Message from: 192.168.30.7:75 - NET-PwrCtrl:NET-CONTROL :NoPass:Err
anelhut.0 | 2022-11-01 16:40:15.432 | info | Command sent successfully
anelhut.0 | 2022-11-01 16:40:15.431 | debug | Password encryption disabled
anelhut.0 | 2022-11-01 16:40:15.429 | debug | Switching Relais Nr. 8 with newState 0 and command Sw_off8
anelhut.0 | 2022-11-01 16:40:15.429 | info | Relais switch command
anelhut.0 | 2022-11-01 16:40:15.428 | info | state anelhut.0.Technikraum.relais.8.Status changed: false (ack = false)-> changed by user
anelhut.0 | 2022-11-01 16:40:15.428 | info | state anelhut.0.Technikraum.relais.8.Status changed: false (ack = false)
anelhut.0 | 2022-11-01 16:37:53.397 | info | state anelhut.0.Technikraum.relais.8.Status changed: 1 (ack = true)
anelhut.0 | 2022-11-01 16:37:53.395 | info | State value to set for "anelhut.0.Technikraum.relais.8.Status" has to be type "boolean" but received type "number"
anelhut.0 | 2022-11-01 16:37:53.372 | info | state anelhut.0.Technikraum.relais.7.Status changed: 1 (ack = true)
anelhut.0 | 2022-11-01 16:37:53.369 | info | state anelhut.0.Technikraum.relais.6.Status changed: 1 (ack = true)
anelhut.0 | 2022-11-01 16:37:53.368 | info | state anelhut.0.Technikraum.relais.5.Status changed: 1 (ack = true)
anelhut.0 | 2022-11-01 16:37:53.368 | info | state anelhut.0.Technikraum.relais.4.Status changed: 1 (ack = true)
anelhut.0 | 2022-11-01 16:37:53.367 | info | state anelhut.0.Technikraum.relais.3.Status changed: 1 (ack = true)
anelhut.0 | 2022-11-01 16:37:53.366 | info | state anelhut.0.Technikraum.relais.2.Status changed: 1 (ack = true)
anelhut.0 | 2022-11-01 16:37:53.366 | info | state anelhut.0.Technikraum.relais.1.Status changed: 1 (ack = true)
anelhut.0 | 2022-11-01 16:37:53.365 | info | state anelhut.0.Technikraum.relais.8.Status changed: 1 (ack = true)
anelhut.0 | 2022-11-01 16:37:53.365 | info | state anelhut.0.Technikraum.relais.7.Status changed: 1 (ack = true)
anelhut.0 | 2022-11-01 16:37:53.364 | info | state anelhut.0.Technikraum.relais.6.Status changed: 1 (ack = true)
anelhut.0 | 2022-11-01 16:37:53.363 | info | state anelhut.0.Technikraum.relais.5.Status changed: 1 (ack = true)
anelhut.0 | 2022-11-01 16:37:53.363 | info | state anelhut.0.Technikraum.relais.4.Status changed: 1 (ack = true)
anelhut.0 | 2022-11-01 16:37:53.362 | info | state anelhut.0.Technikraum.relais.3.Status changed: 1 (ack = true)
anelhut.0 | 2022-11-01 16:37:53.361 | info | state anelhut.0.Technikraum.relais.2.Status changed: 1 (ack = true)
anelhut.0 | 2022-11-01 16:37:53.360 | info | state anelhut.0.Technikraum.relais.1.Status changed: 1 (ack = true)
anelhut.0 | 2022-11-01 16:37:53.353 | info | State value to set for "anelhut.0.Technikraum.relais.7.Status" has to be type "boolean" but received type "number"
anelhut.0 | 2022-11-01 16:37:53.349 | info | State value to set for "anelhut.0.Technikraum.relais.6.Status" has to be type "boolean" but received type "number"
anelhut.0 | 2022-11-01 16:37:53.347 | info | State value to set for "anelhut.0.Technikraum.relais.5.Status" has to be type "boolean" but received type "number"
anelhut.0 | 2022-11-01 16:37:53.347 | info | State value to set for "anelhut.0.Technikraum.relais.4.Status" has to be type "boolean" but received type "number"
anelhut.0 | 2022-11-01 16:37:53.347 | info | State value to set for "anelhut.0.Technikraum.relais.3.Status" has to be type "boolean" but received type "number"
anelhut.0 | 2022-11-01 16:37:53.346 | info | State value to set for "anelhut.0.Technikraum.relais.2.Status" has to be type "boolean" but received type "number"
anelhut.0 | 2022-11-01 16:37:53.346 | info | State value to set for "anelhut.0.Technikraum.relais.1.Status" has to be type "boolean" but received type "number"
anelhut.0 | 2022-11-01 16:37:53.346 | info | State value to set for "anelhut.0.Technikraum.relais.8.Status" has to be type "boolean" but received type "number"
anelhut.0 | 2022-11-01 16:37:53.346 | info | State value to set for "anelhut.0.Technikraum.relais.7.Status" has to be type "boolean" but received type "number"
anelhut.0 | 2022-11-01 16:37:53.345 | info | State value to set for "anelhut.0.Technikraum.relais.6.Status" has to be type "boolean" but received type "number"
anelhut.0 | 2022-11-01 16:37:53.345 | info | State value to set for "anelhut.0.Technikraum.relais.5.Status" has to be type "boolean" but received type "number"
anelhut.0 | 2022-11-01 16:37:53.345 | info | State value to set for "anelhut.0.Technikraum.relais.4.Status" has to be type "boolean" but received type "number"
anelhut.0 | 2022-11-01 16:37:53.345 | info | State value to set for "anelhut.0.Technikraum.relais.3.Status" has to be type "boolean" but received type "number"
anelhut.0 | 2022-11-01 16:37:53.345 | info | State value to set for "anelhut.0.Technikraum.relais.2.Status" has to be type "boolean" but received type "number"
anelhut.0 | 2022-11-01 16:37:53.344 | info | State value to set for "anelhut.0.Technikraum.relais.1.Status" has to be type "boolean" but received type "number"
anelhut.0 | 2022-11-01 16:37:53.333 | info | undefined is not a valid state value for id "anelhut.0.Technikraum.sensor.Sensor_1_Brightness"
anelhut.0 | 2022-11-01 16:37:53.332 | info | undefined is not a valid state value for id "anelhut.0.Technikraum.sensor.Sensor_1_Brightness"
anelhut.0 | 2022-11-01 16:37:53.330 | info | undefined is not a valid state value for id "anelhut.0.Technikraum.sensor.Sensor_1_Humidity"
anelhut.0 | 2022-11-01 16:37:53.329 | info | undefined is not a valid state value for id "anelhut.0.Technikraum.sensor.Sensor_1_Humidity"
anelhut.0 | 2022-11-01 16:37:53.328 | info | undefined is not a valid state value for id "anelhut.0.Technikraum.sensor.Sensor_1_Temperature"
anelhut.0 | 2022-11-01 16:37:53.327 | info | undefined is not a valid state value for id "anelhut.0.Technikraum.sensor.Sensor_1_Temperature"
anelhut.0 | 2022-11-01 16:37:53.323 | info | undefined is not a valid state value for id "anelhut.0.Technikraum.power.PowerFactor"
anelhut.0 | 2022-11-01 16:37:53.322 | info | undefined is not a valid state value for id "anelhut.0.Technikraum.power.PowerFactor"
anelhut.0 | 2022-11-01 16:37:53.320 | info | undefined is not a valid state value for id "anelhut.0.Technikraum.power.ReactivePower"
anelhut.0 | 2022-11-01 16:37:53.318 | info | undefined is not a valid state value for id "anelhut.0.Technikraum.power.ReactivePower"
anelhut.0 | 2022-11-01 16:37:53.316 | info | undefined is not a valid state value for id "anelhut.0.Technikraum.power.ApparentPower"
anelhut.0 | 2022-11-01 16:37:53.314 | info | undefined is not a valid state value for id "anelhut.0.Technikraum.power.ApparentPower"
anelhut.0 | 2022-11-01 16:37:53.312 | info | undefined is not a valid state value for id "anelhut.0.Technikraum.power.ActivePower"
anelhut.0 | 2022-11-01 16:37:53.310 | info | undefined is not a valid state value for id "anelhut.0.Technikraum.power.ActivePower"
anelhut.0 | 2022-11-01 16:37:53.308 | info | undefined is not a valid state value for id "anelhut.0.Technikraum.power.LineFrequency"
anelhut.0 | 2022-11-01 16:37:53.306 | info | undefined is not a valid state value for id "anelhut.0.Technikraum.power.LineFrequency"
anelhut.0 | 2022-11-01 16:37:53.303 | info | undefined is not a valid state value for id "anelhut.0.Technikraum.power.CurrentRMS"
anelhut.0 | 2022-11-01 16:37:53.301 | info | undefined is not a valid state value for id "anelhut.0.Technikraum.power.CurrentRMS"
anelhut.0 | 2022-11-01 16:37:53.295 | info | undefined is not a valid state value for id "anelhut.0.Technikraum.power.VoltageRMS"
anelhut.0 | 2022-11-01 16:37:53.293 | info | undefined is not a valid state value for id "anelhut.0.Technikraum.power.VoltageRMS"
anelhut.0 | 2022-11-01 16:37:53.126 | debug | New hut status update: {"DeviceType":"NET-PwrCtrl","DeviceName":"NET-CONTROL","IP":"192.168.30.7","Netmask":"255.255.255.0","Gateway":"192.168.30.254","MacAdress":"00:04:A3:14:03:76","Relais":[{"RelaisNumber":1,"Name":"Modem","Status":1},{"RelaisNumber":2,"Name":"Firewall","Status":1},{"RelaisNumber":3,"Name":"Unifi Switch","Status":1},{"RelaisNumber":4,"Name":"frei","Status":1},{"RelaisNumber":5,"Name":"Raspimatic","Status":1},{"RelaisNumber":6,"Name":"Weatherman","Status":1},{"RelaisNumber":7,"Name":"Sonos","Status":1},{"RelaisNumber":8,"Name":"Dayton","Status":1}],"Blocked":0,"HttpPort":80,"Temperature":24.7,"Type":"ADV","IO":[],"Firmware":"NET-PWRCTRL_07.1","PowerMeasurement":false,"Sensor_1_Ready":false,"XOR_USER_Password":true,"LastUpdate":"11/1/2022, 4:37:53 PM"}
anelhut.0 | 2022-11-01 16:37:53.126 | debug | New Message from: 192.168.30.7:75 - NET-PwrCtrl:NET-CONTROL :192.168.30.7:255.255.255.0:192.168.30.254:0.4.163.20.3.118:Modem,1:Firewall,1:Unifi Switch,1:frei,1:Raspimatic,1:Weatherman,1:Sonos,1:Dayton,1:0:80:IO.1,0,0:IO.2,0,0:IO.3,0,0:IO.4,0,0:IO.5,0,0:IO.6,0,0:IO.7,0,0:IO.8,0,0:24.7�C:NET-PWRCTRL_07.1:a:n:xor:
anelhut.0 | 2022-11-01 16:37:53.125 | debug | New hut status update: {"DeviceType":"NET-PwrCtrl","DeviceName":"NET-CONTROL","IP":"192.168.30.7","Netmask":"255.255.255.0","Gateway":"192.168.30.254","MacAdress":"00:04:A3:14:03:76","Relais":[{"RelaisNumber":1,"Name":"Modem","Status":1},{"RelaisNumber":2,"Name":"Firewall","Status":1},{"RelaisNumber":3,"Name":"Unifi Switch","Status":1},{"RelaisNumber":4,"Name":"frei","Status":1},{"RelaisNumber":5,"Name":"Raspimatic","Status":1},{"RelaisNumber":6,"Name":"Weatherman","Status":1},{"RelaisNumber":7,"Name":"Sonos","Status":1},{"RelaisNumber":8,"Name":"Dayton","Status":1}],"Blocked":0,"HttpPort":80,"Temperature":24.7,"Type":"ADV","IO":[],"Firmware":"NET-PWRCTRL_07.1","PowerMeasurement":false,"Sensor_1_Ready":false,"XOR_USER_Password":true,"LastUpdate":"11/1/2022, 4:37:53 PM"}
anelhut.0 | 2022-11-01 16:37:53.106 | debug | New Message from: 192.168.30.7:75 - NET-PwrCtrl:NET-CONTROL :192.168.30.7:255.255.255.0:192.168.30.254:0.4.163.20.3.118:Modem,1:Firewall,1:Unifi Switch,1:frei,1:Raspimatic,1:Weatherman,1:Sonos,1:Dayton,1:0:80:IO.1,0,0:IO.2,0,0:IO.3,0,0:IO.4,0,0:IO.5,0,0:IO.6,0,0:IO.7,0,0:IO.8,0,0:24.7�C:NET-PWRCTRL_07.1:a:n:xor:
anelhut.0 | 2022-11-01 16:37:19.564 | info | check group user admin group admin: false
anelhut.0 | 2022-11-01 16:37:19.562 | info | check user admin pw iobroker: false,system.user.admin
anelhut.0 | 2022-11-01 16:37:19.458 | debug | Starting UDP listener on port: 2078
anelhut.0 | 2022-11-01 16:37:19.458 | debug | AnelHutCommunication constructor. this.userPasswordXOR = false
anelhut.0 | 2022-11-01 16:37:19.457 | debug | UserPasswordXOR: false
anelhut.0 | 2022-11-01 16:37:19.457 | info | Init device Technikraum
anelhut.0 | 2022-11-01 16:37:19.411 | info | Adapter anelhut initialized
anelhut.0 | 2022-11-01 16:37:19.410 | info | Found device in config: Technikraum \| 192.168.30.7
anelhut.0 | 2022-11-01 16:37:19.410 | info | Found: 1 devices in configuration
anelhut.0 | 2022-11-01 16:37:19.410 | info | Adapter anelhut starting...
anelhut.0 | 2022-11-01 16:37:19.399 | info | starting. Version 1.0.10 in /opt/iobroker/node_modules/iobroker.anelhut, node: v16.16.0, js-controller: 4.0.23
anelhut.0 | 2022-11-01 16:37:19.176 | debug | States connected to redis: 127.0.0.1:9000
anelhut.0 | 2022-11-01 16:37:19.125 | debug | States create User PubSub Client
anelhut.0 | 2022-11-01 16:37:19.125 | debug | States create System PubSub Client
anelhut.0 | 2022-11-01 16:37:19.098 | debug | Redis States: Use Redis connection: 127.0.0.1:9000
anelhut.0 | 2022-11-01 16:37:19.056 | debug | Objects connected to redis: 127.0.0.1:9001
anelhut.0 | 2022-11-01 16:37:19.050 | debug | Objects client initialize lua scripts
anelhut.0 | 2022-11-01 16:37:18.963 | debug | Objects create User PubSub Client
anelhut.0 | 2022-11-01 16:37:18.962 | debug | Objects create System PubSub Client
anelhut.0 | 2022-11-01 16:37:18.961 | debug | Objects client ready ... initialize now
anelhut.0 | 2022-11-01 16:37:18.912 | debug | Redis Objects: Use Redis connection: 127.0.0.1:9001
anelhut.0 | 2022-11-01 16:37:15.453 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
anelhut.0 | 2022-11-01 16:37:15.452 | info | terminating
anelhut.0 | 2022-11-01 16:37:15.450 | info | Got terminate signal TERMINATE_YOURSELF
anelhut.0 | 2022-11-01 16:35:13.813 | info | check group user admin group admin: false
anelhut.0 | 2022-11-01 16:35:13.811 | info | check user admin pw iobroker: false,system.user.admin
anelhut.0 | 2022-11-01 16:35:13.711 | info | Init device Technikraum
anelhut.0 | 2022-11-01 16:35:13.669 | info | Adapter anelhut initialized
anelhut.0 | 2022-11-01 16:35:13.668 | info | Found device in config: Technikraum \| 192.168.30.7
anelhut.0 | 2022-11-01 16:35:13.668 | info | Found: 1 devices in configuration
anelhut.0 | 2022-11-01 16:35:13.667 | info | Adapter anelhut starting...
anelhut.0 | 2022-11-01 16:35:13.654 | info | starting. Version 1.0.10 in /opt/iobroker/node_modules/iobroker.anelhut, node: v16.16.0, js-controller: 4.0.23


</body>
</html>`

**Comment by dan1-de** [comment]
HI @Qlink84, 
have you entered the user and password in the adapter configuration. 
In the logs I can see that no user and password was given (see: error | Decode Message Error: NoPass").
Please enter your username/password in the adapter configuration or use the default credentials (admin/anel).
Without username/password it's not working.


![image](https://user-images.githubusercontent.com/52854781/200123180-bbf7d9c4-e8fb-4609-aeb4-80e4e60195d1.png)

**Comment by Qlink84** [comment]
Yes i have entered it correctly. the error msg is because i've tried with different user, but changed it then back to the real one.
If user/pass would be the problem i guess i wouldn't even see the relais status, would i ?

When i turn relais on/off through anel webif, status in iobroker objects change correctly.
The only problem is i can't control the relais through iobroker...
if i go to objects in iobroker and manually set relais 8 to false
![image](https://user-images.githubusercontent.com/15886027/200135949-774c943a-4d0b-42f4-b67c-52e11ba23fba.png)
i get correct info in iobroker log
![image](https://user-images.githubusercontent.com/15886027/200135979-02f2999a-5643-422e-8082-0065a984a943.png)

but nothing changes at the anel sockets
![image](https://user-images.githubusercontent.com/15886027/200136077-bd2a07a4-cb76-4c76-b39b-7b80f2596cd6.png)

**Comment by dan1-de** [comment]
Hi @Qlink84 ,

for reading only there is no user/password needed. 
Because of that the status refresh is working well. 
For controlling the relais the username/password is required.

You can try in manual mode with this command to verify if it's working without the adapter:

General Command Structure: echo "Sw_on%relaisNumber%%user%%password%" | nc -4u %yourAnelIP% 75

Example: echo "Sw_on2adminanel" | nc -4u 192.168.30.7 75
This example turns the Relais Nr. 2 on.
To turn it off you can use this command: echo "Sw_on2adminanel" | nc -4u 192.168.30.7 75

Can you check please if this is working.
Please make sure that you are using the admin user. If you use another user make sure that all the permissions are set in the Anel Webinterface.

![image](https://user-images.githubusercontent.com/52854781/200327702-f0fd690b-571b-483b-a8a9-c188ccc284fe.png)

**Comment by Qlink84** [comment]
i'm using default admin/anel login now, but it's still not working through adapter... no change in behavior when i try to set relais status manually to true or false in iobroker objects...

echo "Sw_off8adminanel" | nc -4u 192.168.30.7 75 works without a problem 
http://192.168.30.7/?Sw_on=6,adminanel works also without a problem

**Comment by Qlink84** [comment]
it's running on a hyper-v ubuntu vm, but the echo "Sw_off8adminanel" | nc -4u 192.168.30.7 75 command works fine executed inside the vm, so the connection from iobroker to anel should be no issue right ?

**Comment by dan1-de** [comment]
Yes, that was exactly the background of my question.
If it's working from inside the vm everything should be set up correctly.

**Comment by dan1-de** [comment]
In addition you could install the latest dev build of the adapter using this url: 
https://github.com/dan1-de/ioBroker.anelhut/tarball/dev
Installieren aus eigener URL -> Benutzerdefiniert

I've added some additional log messages. 
Please set the logging to debug and provide me the logs. Make sure that there is at least one switch command visible in the logs.

**Comment by Qlink84** [comment]
installed dev build, but nothing has changed really in log output (tried to change relais 4 via iobroker objects)

`<html>
<body>


anelhut.0 | 2022-11-08 06:52:38.404 | info | state anelhut.0.Technikraum.relais.4.Status changed: true (ack = true)
-- | -- | -- | --
anelhut.0 | 2022-11-08 06:52:06.699 | info | state anelhut.0.Technikraum.relais.4.Status changed: false (ack = true)
anelhut.0 | 2022-11-08 06:51:12.558 | info | state anelhut.0.Technikraum.relais.8.Status changed: true (ack = true)
anelhut.0 | 2022-11-08 06:51:12.558 | info | state anelhut.0.Technikraum.relais.7.Status changed: true (ack = true)
anelhut.0 | 2022-11-08 06:51:12.557 | info | state anelhut.0.Technikraum.relais.6.Status changed: true (ack = true)
anelhut.0 | 2022-11-08 06:51:12.556 | info | state anelhut.0.Technikraum.relais.5.Status changed: true (ack = true)
anelhut.0 | 2022-11-08 06:51:12.555 | info | state anelhut.0.Technikraum.relais.4.Status changed: true (ack = true)
anelhut.0 | 2022-11-08 06:51:12.554 | info | state anelhut.0.Technikraum.relais.3.Status changed: true (ack = true)
anelhut.0 | 2022-11-08 06:51:12.554 | info | state anelhut.0.Technikraum.relais.2.Status changed: true (ack = true)
anelhut.0 | 2022-11-08 06:51:12.553 | info | state anelhut.0.Technikraum.relais.1.Status changed: true (ack = true)
anelhut.0 | 2022-11-08 06:51:12.552 | info | state anelhut.0.Technikraum.relais.8.Status changed: true (ack = true)
anelhut.0 | 2022-11-08 06:51:12.552 | info | state anelhut.0.Technikraum.relais.7.Status changed: true (ack = true)
anelhut.0 | 2022-11-08 06:51:12.551 | info | state anelhut.0.Technikraum.relais.6.Status changed: true (ack = true)
anelhut.0 | 2022-11-08 06:51:12.550 | info | state anelhut.0.Technikraum.relais.5.Status changed: true (ack = true)
anelhut.0 | 2022-11-08 06:51:12.549 | info | state anelhut.0.Technikraum.relais.4.Status changed: true (ack = true)
anelhut.0 | 2022-11-08 06:51:12.545 | info | state anelhut.0.Technikraum.relais.3.Status changed: true (ack = true)
anelhut.0 | 2022-11-08 06:51:12.545 | info | state anelhut.0.Technikraum.relais.2.Status changed: true (ack = true)
anelhut.0 | 2022-11-08 06:51:12.544 | info | state anelhut.0.Technikraum.relais.1.Status changed: true (ack = true)
anelhut.0 | 2022-11-08 06:51:12.479 | info | undefined is not a valid state value for id "anelhut.0.Technikraum.sensor.Sensor_1_Brightness"
anelhut.0 | 2022-11-08 06:51:12.478 | info | undefined is not a valid state value for id "anelhut.0.Technikraum.sensor.Sensor_1_Brightness"
anelhut.0 | 2022-11-08 06:51:12.475 | info | undefined is not a valid state value for id "anelhut.0.Technikraum.sensor.Sensor_1_Humidity"
anelhut.0 | 2022-11-08 06:51:12.474 | info | undefined is not a valid state value for id "anelhut.0.Technikraum.sensor.Sensor_1_Humidity"
anelhut.0 | 2022-11-08 06:51:12.472 | info | undefined is not a valid state value for id "anelhut.0.Technikraum.sensor.Sensor_1_Temperature"
anelhut.0 | 2022-11-08 06:51:12.472 | info | undefined is not a valid state value for id "anelhut.0.Technikraum.sensor.Sensor_1_Temperature"
anelhut.0 | 2022-11-08 06:51:12.467 | info | undefined is not a valid state value for id "anelhut.0.Technikraum.power.PowerFactor"
anelhut.0 | 2022-11-08 06:51:12.465 | info | undefined is not a valid state value for id "anelhut.0.Technikraum.power.PowerFactor"
anelhut.0 | 2022-11-08 06:51:12.465 | info | undefined is not a valid state value for id "anelhut.0.Technikraum.power.ReactivePower"
anelhut.0 | 2022-11-08 06:51:12.462 | info | undefined is not a valid state value for id "anelhut.0.Technikraum.power.ReactivePower"
anelhut.0 | 2022-11-08 06:51:12.462 | info | undefined is not a valid state value for id "anelhut.0.Technikraum.power.ApparentPower"
anelhut.0 | 2022-11-08 06:51:12.460 | info | undefined is not a valid state value for id "anelhut.0.Technikraum.power.ApparentPower"
anelhut.0 | 2022-11-08 06:51:12.459 | info | undefined is not a valid state value for id "anelhut.0.Technikraum.power.ActivePower"
anelhut.0 | 2022-11-08 06:51:12.457 | info | undefined is not a valid state value for id "anelhut.0.Technikraum.power.ActivePower"
anelhut.0 | 2022-11-08 06:51:12.456 | info | undefined is not a valid state value for id "anelhut.0.Technikraum.power.LineFrequency"
anelhut.0 | 2022-11-08 06:51:12.454 | info | undefined is not a valid state value for id "anelhut.0.Technikraum.power.LineFrequency"
anelhut.0 | 2022-11-08 06:51:12.454 | info | undefined is not a valid state value for id "anelhut.0.Technikraum.power.CurrentRMS"
anelhut.0 | 2022-11-08 06:51:12.453 | info | undefined is not a valid state value for id "anelhut.0.Technikraum.power.CurrentRMS"
anelhut.0 | 2022-11-08 06:51:12.449 | info | undefined is not a valid state value for id "anelhut.0.Technikraum.power.VoltageRMS"
anelhut.0 | 2022-11-08 06:51:12.449 | info | undefined is not a valid state value for id "anelhut.0.Technikraum.power.VoltageRMS"
anelhut.0 | 2022-11-08 06:51:12.362 | debug | New hut status update: {"DeviceType":"NET-PwrCtrl","DeviceName":"NET-CONTROL","IP":"192.168.30.7","Netmask":"255.255.255.0","Gateway":"192.168.30.254","MacAdress":"00:04:A3:14:03:76","Relais":[{"RelaisNumber":1,"Name":"Modem","Status":1},{"RelaisNumber":2,"Name":"Firewall","Status":1},{"RelaisNumber":3,"Name":"Unifi Switch","Status":1},{"RelaisNumber":4,"Name":"frei","Status":1},{"RelaisNumber":5,"Name":"Raspimatic","Status":1},{"RelaisNumber":6,"Name":"Weatherman","Status":1},{"RelaisNumber":7,"Name":"Sonos","Status":1},{"RelaisNumber":8,"Name":"Dayton","Status":1}],"Blocked":0,"HttpPort":80,"Temperature":24.4,"Type":"ADV","IO":[],"Firmware":"NET-PWRCTRL_07.1","PowerMeasurement":false,"Sensor_1_Ready":false,"XOR_USER_Password":true,"LastUpdate":"11/8/2022, 6:51:12 AM"}
anelhut.0 | 2022-11-08 06:51:12.362 | debug | New Message from: 192.168.30.7:75 - NET-PwrCtrl:NET-CONTROL :192.168.30.7:255.255.255.0:192.168.30.254:0.4.163.20.3.118:Modem,1:Firewall,1:Unifi Switch,1:frei,1:Raspimatic,1:Weatherman,1:Sonos,1:Dayton,1:0:80:IO.1,0,0:IO.2,0,0:IO.3,0,0:IO.4,0,0:IO.5,0,0:IO.6,0,0:IO.7,0,0:IO.8,0,0:24.4�C:NET-PWRCTRL_07.1:a:n:xor:
anelhut.0 | 2022-11-08 06:51:12.361 | debug | New hut status update: {"DeviceType":"NET-PwrCtrl","DeviceName":"NET-CONTROL","IP":"192.168.30.7","Netmask":"255.255.255.0","Gateway":"192.168.30.254","MacAdress":"00:04:A3:14:03:76","Relais":[{"RelaisNumber":1,"Name":"Modem","Status":1},{"RelaisNumber":2,"Name":"Firewall","Status":1},{"RelaisNumber":3,"Name":"Unifi Switch","Status":1},{"RelaisNumber":4,"Name":"frei","Status":1},{"RelaisNumber":5,"Name":"Raspimatic","Status":1},{"RelaisNumber":6,"Name":"Weatherman","Status":1},{"RelaisNumber":7,"Name":"Sonos","Status":1},{"RelaisNumber":8,"Name":"Dayton","Status":1}],"Blocked":0,"HttpPort":80,"Temperature":24.4,"Type":"ADV","IO":[],"Firmware":"NET-PWRCTRL_07.1","PowerMeasurement":false,"Sensor_1_Ready":false,"XOR_USER_Password":true,"LastUpdate":"11/8/2022, 6:51:12 AM"}
anelhut.0 | 2022-11-08 06:51:12.360 | debug | New Message from: 192.168.30.7:75 - NET-PwrCtrl:NET-CONTROL :192.168.30.7:255.255.255.0:192.168.30.254:0.4.163.20.3.118:Modem,1:Firewall,1:Unifi Switch,1:frei,1:Raspimatic,1:Weatherman,1:Sonos,1:Dayton,1:0:80:IO.1,0,0:IO.2,0,0:IO.3,0,0:IO.4,0,0:IO.5,0,0:IO.6,0,0:IO.7,0,0:IO.8,0,0:24.4�C:NET-PWRCTRL_07.1:a:n:xor:


</body>
</html>`

maybe a teamviewer session would be better ? today, ~18:00 o'clock ?

**Comment by Qlink84** [comment]
update: it seems like controlling relais through blockly script works now since adapter update.

however, controlling relais manually through iobroker objects still doesn't work

**Comment by dan1-de** [comment]
Ok very strange. Could you stop the adapter and delete all the objects created under anelhut.0 and start the adapter again.

**Comment by dan1-de** [comment]
If you change a status manually via iobroker admin you have to make sure that the ack is set to false. 
ack=false means that the adapter has something to do. ack=true is if the adapter updates a state

**Comment by Qlink84** [comment]
omg, that was the problem... i always ticked ack ...🤐

works now, thank you for that information.

now the only "problem" is that temperature is not read through the adapter...

**Comment by dan1-de** [comment]
No problem. The main thing is that it works now.
There is no sensor data visible in the udp respone of your device. 
Have you enabled the sensor in the webinterface ? 
Can you see the sensor data in the webinterface ? 


![image](https://user-images.githubusercontent.com/52854781/200898179-b00ae6ed-de16-4ab5-951b-d3461b49f5eb.png)

**Comment by Qlink84** [comment]
Seems like i don't have this sub menu...
it looks like this on my ADV:
![image](https://user-images.githubusercontent.com/15886027/200900798-121b6ef5-c5ed-452b-a9d0-763bdf467895.png)
![image](https://user-images.githubusercontent.com/15886027/200901051-bd2713ff-d3ed-42e0-9624-983900796280.png)

**Comment by dan1-de** [comment]
Ah ok. You have no sensor connected. The temperature measurement is available by default.
Please check the object structure of the adapter again this value should be available.

**Comment by Qlink84** [comment]
got it. wasn't looking under general but under sensor... 🤭
thanks again for your help.

you can close this issue.

p.s. the only "cosmetical" thing is, that every time a relais status changes i get a lot of theses messages in iobroker log, because i dont have these values with my PWR ADV:
![image](https://user-images.githubusercontent.com/15886027/201010752-568d31c2-71f7-47d6-96b2-d2e5aa189a98.png)

**Comment by Qlink84** [comment]
p.p.s auch wenn sich nur ein relais ändert wird im log immer die komplette Palette anzeigt:

![image](https://user-images.githubusercontent.com/15886027/201016463-834c61f8-0fa2-4d88-a5bb-bb88fccf3faf.png)

**Comment by dan1-de** [comment]
Ich werde das Ticket schließen. Das mit dem Sensor könnte man noch optimieren.

Es werden immer alle Relais angezeigt, das  bei jeder Anfrage der Status aller Relais gesendet wird. 

Sind beides nur kosmetische Fehler die ich ihm Rahmen des nächsten Release beheben werde.
