### ISSUE TITLE
No object structure created

### ISSUE THREAD

**Issue by ezehosh** [dan1-de/ioBroker.anelhut#9]
After installing the first entry in the device list device is shown under Objects as a 1-liner with no structure.

Log shows device found and full information record retrieved but no corresponding object structure created.

![Anel 1](https://user-images.githubusercontent.com/69955941/111430549-cf222700-86fa-11eb-923c-bf161eb879b6.JPG)
![Anel 2](https://user-images.githubusercontent.com/69955941/111430555-d1848100-86fa-11eb-88bf-1259c57f5638.JPG)
![Anel 3](https://user-images.githubusercontent.com/69955941/111430843-43f56100-86fb-11eb-82e1-1263dd1f4e19.JPG)

**Comment by dan1-de** [comment]
Thank you for feedback.
Have you tried to click on the refresh button in the object list? 

Sometimes it takes some time to create the object structure.

**Comment by ezehosh** [comment]
Reinstalling the adapter 3 times did the trick. Don´t know why.

 

Thx

**Comment by dan1-de** [comment]
Ok this is very strange.
I tested on 3 different computers Linux and Windows without any problems.

But I'm happy when it works now.

**Comment by ezehosh** [comment]
Me too. Nice piece of work.
